### ISSUE TITLE
Warehouse not readily selling ECells to own factories

### ISSUE THREAD

**Issue by DeeparthGupta** [mbleichner/x4-warehouse-fleets#4]
I'm going to paste here what I posted on Nexusmods page

> While collection from my factories seems to work the warehouse doesn't supply my factories with raw materials leaving them > starved. It also seems to use too few ships. Its using 2 M ships for 3 factories and a warehouse. I've given it a lot more. I've lowered the  minimum required cargo to 20% but it seems to have no effect.
> 
> Edit: This seems to affect Energy cells only. I built a meat factory. The warehouse sells water to it but not energy cells. `

Now the first 2 factories seem to be getting supplied but the new meat factory isn't even though it is setup like the other factories and has 0 e cells. It was sold water once and nothing. The warehouse seems to be ignoring it. I've tried setting individual stations as targets as well as the entire sector my factories are in no effect. I have resorted to manual orders of e cells but that will get tedius quickly.

**Comment by mbleichner** [comment]
Sorry, I'm not very active on Nexus as you probably noticed.

Check if the station created a buy order for energy cells. Also check if the cargo space for energy cells is large enough. The mod only always balances resources until an equilibrium of percentages is reached, which can be a problem for wares that take very little cargo room like energy cells.
Assume, your warehouse is 10% full. Also assume, your meat factory can store the same volume of energy cells as the warehouse. The highest amount that will ever be transferred is half of the energy cells in your warehouse, because then an equilibrium of 5% - 5% is reached. If those 5% amount to a volume less than the ship cargo threshold, it will never be scheduled.
Usually the fix is to build additional cargo modules and/or increase the share of cargo space for energy cells manually.

If this also doesn't help, you could enable debug logging:
- Add the following arguments when starting the game: `-debug all -logfile debuglog.txt -scriptlogfiles scriptlogs`
- And enable debug logs for the mod: set the debugchance variable to 100 in line 11 of md/warehousefleets.xml.

This will create a file for every ship, listing the possible trades that are being considered. Enabling debug logs makes the game super stuttery though.

**Comment by DeeparthGupta** [comment]
I don't see this problem in new games. In the save I where the problem existed I had another trading mod that I uninstalled before installing this.
