### ISSUE TITLE
Feature: Sale function

### ISSUE THREAD

**Issue by GameBurrow** [mbleichner/x4-warehouse-fleets#6]
Stumbled upon this mod after the `Mules Supply and Warehouses Extended` broke. Love how this mod replaces all the things I used from that.

Only feature that I find is missing and I haven't found any other mod that does it well is:
> **Travel Mule**  
>    This Mule is the ONLY one to care at all about prices and profits! It is the one you will use to sell from your warehouses and other stations to every other faction.  

Essentially set the home warehouse and do not set any targets - meaning sell to any station in the galaxy. Obviously this one should look at profits also.

**Comment by mbleichner** [comment]
It's implicitly covered by the mod - every fleet member cares about making profit, but you have to define your allowed trade targets for each warehouse+ware by setting whitelists/blacklists. (Or else they will maximise "profit" within your own network only)

If you follow the readme, it says to first restrict all trade to your own stations, then specifically allow certain wares to buy/sell by overriding their settings.  If you do this, ships will consider buying from / selling to NPC stations - if it is profitable.

Check the readme carefully. It's all described there, but I admit it's easy to overlook some details because the behavior is somewhat complex and I had to make use of game mechanics that can be a bit obtuse sometimes.
